from algorithms import (
    binaryInsertionSort,
    bitonicSort,
    bogoSort,
    bubbleSort,
    bucketSort,
    cocktailSort,
    combSort,
    countingSort,
    cycleSort,
    exchangeSort,
    gnomeSort,
    heapSort,
    insertionSort,
    mergeSort,
    oddevenSort,
    pancakeSort,
    pigeonholeSort,
    quickSort,
    radixSort,
    selectionSort,
    shellSort,
    slowSort,
    stoogeSort,
    strandSort,
    timSort,
    treeSort,
)

# Map sorting algorithm names to their respective implementations
algorithmsDict = {
    'insertionSort'       : insertionSort,
    'bubbleSort'          : bubbleSort,
    'selectionSort'       : selectionSort,
    'mergeSort'           : mergeSort,
    'quickSort'           : quickSort,
    'quickSortLR'         : quickSort_LR,
    'countingSort'        : countingSort,
    'cocktailSort'        : cocktailSort,
    'cycleSort'           : cycleSort,
    'bogoSort'            : bogoSort,
    'heapSort'            : heapSort,
    'radixSort'           : radixSort,
    'shellSort'           : shellSort,
    'gnomeSort'           : gnomeSort,
    'combSort'            : combSort,
    'bitonicSort'         : bitonicSort,
    'pancakeSort'         : pancakeSort,
    'binaryInsertionSort': binaryInsertionSort,
    'bucketSort'          : bucketSort,
    'timSort'             : timSort,
    'stoogeSort'          : stoogeSort,
    'strandSort'          : strandSort,
    'oddEvenSort'        : oddevenSort,
    'pigeonholeSort'      : pigeonholeSort,
    'exchangeSort'        : exchangeSort,
    'treeSort'            : treeSort,
    'slowSort'            : slowSort,
}
